In [1]:
print("ARRAY in NUMPy")

ARRAY in NUMPy


In [3]:
print("afzal sa ajj baat hui")

afzal sa ajj baat hui


In [5]:
a = np.array9([1,2,3] [ 4,5,6] [7,8,9])
print(a)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12120\2718595681.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array9([1,2,3] [ 4,5,6] [7,8,9])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12120\2718595681.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array9([1,2,3] [ 4,5,6] [7,8,9])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12120\2718595681.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array9([1,2,3] [ 4,5,6] [7,8,9])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12120\2718595681.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array9([1,2

NameError: name 'np' is not defined

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b =np.array([1,2,3], [4,5,6], [7,8,9])
print(b)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [1]:
print("nehaliis back")

nehaliis back


In [2]:
import numpy as np

In [4]:
c = np.array([[1,5,8] , [7,8,9]])
print(c)

[[1 5 8]
 [7 8 9]]


In [7]:
#list multiplication 
list1 = [1,5,9]
print(list1 *2)

[1, 5, 9, 1, 5, 9]


In [9]:
#Array multiplication 
array1 = np.array([4,2,8])
print(array1 * 2)

[ 8  4 16]


In [19]:
import time 

start = time.time()
list1 = [i*2 for i in range(100000) ]
print("/n time of multiplication ", time.time()- start )

start = time.time()
array1 = np.arange(100000) *2 # in (np.arange(start , stop , step))
print("/n time in Array multiply : ", time.time() - start )


print("\n Example of arange")
sequence = np.arange(2 , 101 , 2 )
print(sequence)

/n time of multiplication  0.014108657836914062
/n time in Array multiply :  0.0022771358489990234

 Example of arange
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
zeroes = np.zeros([2,2])# 2,2 represent row and column 
print(zeroes)

[[0. 0.]
 [0. 0.]]


In [13]:
ones = np.ones([4,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# multiply of array 
import numpy as np
constant = np.full([3,3] , 7)
print("\nconstant matrix : " , constant)

ones = np.ones([3,3])
print("\nAll one matrices : " , ones )

print("\n Multiplication of Matrices ")

print("\n multiplication\n",constant * ones)



constant matrix :  [[7 7 7]
 [7 7 7]
 [7 7 7]]

All one matrices :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Multiplication of Matrices 

 multiplication
 [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
random = np.random.random([2,3])
print(random) # in random there number is start from 0 to one only 

[[0.41070128 0.17036449 0.16364799]
 [0.16408942 0.83983518 0.47271471]]


In [27]:
#vector , matrix and tensor 

vector = np.array([1,2,3])
print("this is vector\n", vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("this is matrix =\n",matrix)

tensor = np.array([[[1,2],[3,4]] ,[ [5,6] ,[7,8]]])
print("this is tensort  = \n",tensor)

this is vector
 [1 2 3]
this is matrix =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
this is tensort  = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
arr = np.array([[4,5,8] , 
               [1,2,9]])
print("Shape",arr.shape)
print("Size" ,arr.size)
print("Datatype" ,arr.dtype)
print("Dimension" , arr.ndim)

Shape (2, 3)
Size 6
Datatype int64
Dimension 2


In [9]:
#array reshping
import numpy as np
arr = np.arange(12)
print(arr)
reshaped = arr.reshape((3,4))
print("\n",reshaped)
flattend = reshaped.flatten()
print("\n", flattend)

#ravewl returns veiws instead of copy
ravaled = reshaped.ravel()
print("\n" , ravaled)

#transpose (row ko column mai)
transpose = reshaped.T
print("\n ",transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#concept of slicing in ARRay with simple vector
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])
print("slicing ", arr[2:7])
print("with step", arr[1 : 9: 2] )
print("Negative indexing: ", arr[-3])


slicing  [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing:  7


In [17]:
#it first row  start from 0
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("for specific elment: ",arr[1,2])#
#for taking specificentire row 
print("entire ROW : ",arr[1])
print("for entire column :",arr[:,0]) #for entire column


for specific elment:  6
entire ROW :  [4 5 6]
for entire column : [1 4 7]


In [3]:
#SORTING
arr = np.array([1,4,8,9,67,3,144,2])
print(np.sort(arr))

#sorting of 2d matrix 

arr2_d = np.array([[3,1],
                  [4,3],
                  [1,4]])
print(np.sort(arr2_d, axis = 0))
print("\n")
print(np.sort(arr2_d, axis = 1))


[  1   2   3   4   8   9  67 144]
[[1 1]
 [3 3]
 [4 4]]


[[1 3]
 [3 4]
 [1 4]]


In [ ]:
#filter
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers % 2== 0 ]
print(even)

#filter with mask (we can hold expression in variable )

mask= numbers < 5 
print("number less than 5 : ",numbers[mask])

#indices 
indices = [0,2,4]
print(numbers[indices])


#np.where

result = np.where(numbers>5)
print(numbers[result])



[ 2  4  6  8 10]
number less than 5 :  [1 2 3 4]
[1 3 5]
[ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers<3 , numbers * 2 , numbers)
print(condition_array)
# np.where (condition , if , else ) or (condition , True , False)
example = np.where(numbers>5 ,"true" , 'false')
print(example)

#example by grok 
arr = np.array([1, 2, 3, 4, 5])
x = np.array([10, 20, 30, 40, 50])  # x array
y = np.array([0, 0, 0, 0, 0])       # y array
result = np.where(arr > 3, x, y)
print(result)
# Output: [0 0 0 40 50]


[ 2  4  3  4  5  6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[ 0  0  0 40 50]


In [ ]:
arr1 = np.array([4,5,6])
arr2 = np.array([1,2,3])
print(arr1 +arr2) # it is not okk

add = np.concatenate((arr1,arr2)) #it is ok 

print(add)


[5 7 9]
[4 5 6 1 2 3]


In [8]:
import numpy as np 
#comparebility 
a = np.array([1,2])
b = np.array([3,4 , 5])
print("comparebility |: ",a.shape == b.shape)

comparebility |:  False


In [15]:
#for adding new row column
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]]) #this row will ad on original 

with_new_row = np.vstack((original , new_row))
print(with_new_row)
print("\n")

#for adding new column 
new_col = np.array([[7],[8]])
with_new_column = np.hstack((original , new_col))
print(with_new_column)

[[1 2]
 [3 4]
 [5 6]]


[[1 2 7]
 [3 4 8]]


In [18]:
#for delete 
arr =np.array([1,2,3,4,5,6])
deleted = np.delete(arr , 0 )
print(deleted)


[2 3 4 5 6]
